import tables             # Library to read Nastran HDF5 binary files (.h5)
import pandas as pd       # Library for data manipulation and creating tables (DataFrames)
import numpy as np        # Library for high-performance numerical and matrix calculations
from scipy import optimize # Library containing the Newton-Raphson numerical solver
import matplotlib.pyplot as plt # Standard library for generating 2D graphs/plots
import seaborn as sns     # Advanced visualization library for better-looking charts
import os                 # Library to interact with the Operating System (file paths, deleting files)
import glob               # Library to search for files using pattern matching (e.g., *.h5)
import re                 # Library for Regular Expressions (text pattern matching)
from tqdm import tqdm     # Library to display a progress bar in the terminal
from xlsxwriter.utility import xl_col_to_name # Tool to convert column numbers to Excel letters (e.g., 0 -> A)
import gc                 # Garbage Collector to free up RAM memory manually

# ==============================================================================
# 1. GLOBAL SETTINGS & UTILITIES
# ==============================================================================
MOS_LIMIT_WARNING = 0.2   # Margin of Safety threshold to trigger yellow warning in Excel
SOLVER_TOL = 1e-6         # Tolerance level for the Neuber numerical solver precision
DEF_DISP = {'ID': 'Node ID', 'X': 'Tx', 'Y': 'Ty', 'Z': 'Tz'} # Mapping for displacement columns

def clean_subtitle(text):
    """ Cleans byte strings (e.g., b'force2x') and removes unnecessary quotes """
    # If the text is in byte format, decode it to a normal string
    if isinstance(text, bytes): 
        text = text.decode('utf-8', errors='ignore')
    text = str(text).strip()
    
    # Remove the b'...' or b"..." wrapper usually generated by Nastran
    if (text.startswith("b'") and text.endswith("'")) or (text.startswith('b"') and text.endswith('"')):
        text = text[2:-1]
        
    # Remove any remaining single or double quotes
    text = text.replace("'", "").replace('"', '')
    return text.strip()

def safe_filename(text):
    """ Replaces illegal characters in a string to make it safe for saving as a file name (.png) """
    return re.sub(r'[^A-Za-z0-9_\-\.]', '_', text)

def parse_element_ranges(range_str):
    """ Converts a user input string like '1-500, 1001' into a Python list of integers """
    element_ids = set() # Use a set to automatically prevent duplicate IDs
    parts = range_str.split(',') # Split input by comma
    for part in parts:
        part = part.strip()
        if '-' in part: # If it's a range (e.g., 1-500)
            try:
                start_str, end_str = part.split('-')
                # Add all numbers from start to end into the set
                element_ids.update(range(int(start_str.strip()), int(end_str.strip()) + 1))
            except ValueError: 
                pass
        elif part.isdigit(): # If it's a single number
            element_ids.add(int(part))
    return list(element_ids) # Return as a standard list

# ==============================================================================
# 2. PHYSICS & FORMULAS (CORE LOGIC)
# ==============================================================================
def get_strain_ramberg(stress, E, Fty, n):
    """ Calculates the total strain using the Ramberg-Osgood material model """
    s = np.asarray(stress) 
    elastic = s / E # Calculate elastic strain (Hooke's Law)
    # Calculate plastic strain (only applies if stress is greater than 0)
    plastic = np.where(s > 0, 0.002 * ((s / Fty)**n), 0.0)
    return elastic + plastic # Total strain = Elastic + Plastic

def solve_neuber_mmpds(sigma_linear, E, Fty, n):
    """ Solves Neuber's rule to find the true local stress using Newton-Raphson method """
    energy_target = (sigma_linear**2) / E # Calculate the theoretical linear strain energy
    
    # Define the difference function that the solver needs to minimize to zero
    def func_diff(s_neu):
        if s_neu <= 0: 
            return -energy_target 
        e_tot = get_strain_ramberg(s_neu, E, Fty, n) # Get total strain for current guessed stress
        return (s_neu * e_tot) - energy_target # Difference between Neuber energy and Linear energy
        
    try: 
        # Use SciPy's Newton-Raphson optimizer to find the root (true stress)
        return optimize.newton(func_diff, x0=sigma_linear*0.9, maxiter=50, tol=SOLVER_TOL)
    except: 
        # If solver fails to converge, return the original linear stress as a fallback
        return sigma_linear 

# ==============================================================================
# 3. H5 DATA MINING & BDF SCANNER
# ==============================================================================
def parse_bdf_subtitles(bdf_filepath):
    """ Scans the .bdf file to extract custom Load Case names (Subtitles) defined in Patran """
    subcase_dict = {}
    if not bdf_filepath or not os.path.exists(bdf_filepath): 
        return subcase_dict
    
    print(f"    [+] Scanning Subtitles from: {os.path.basename(bdf_filepath)}...")
    current_subcase = None
    try:
        # Open and read the BDF text file line by line
        with open(bdf_filepath, 'r', errors='ignore') as f:
            for line in f:
                line = line.strip()
                if line.startswith("SUBCASE"): # Detect subcase block
                    try: 
                        current_subcase = int(line.split()[1]) # Extract the subcase ID number
                    except: 
                        pass
                elif line.startswith("SUBTITLE") and current_subcase is not None: # Detect subtitle
                    if "=" in line:
                        subtitle_text = line.split("=")[1].strip() # Extract text after '='
                        # Save the cleaned subtitle to the dictionary
                        subcase_dict[current_subcase] = f"Subcase {current_subcase}: {clean_subtitle(subtitle_text)}"
    except Exception: 
        pass
    
    return subcase_dict

def extract_h5_data(input_file, bdf_file=None):
    """ Main function to extract displacement and stress data from the Nastran .h5 database """
    print(f"    [+] Reading H5 Database: {os.path.basename(input_file)} ...")
    h5 = tables.open_file(input_file, mode="r") # Open the HDF5 file in read mode
    df_disp = pd.DataFrame() 
    
    # Run the BDF scanner to get user-defined names
    bdf_subtitles = parse_bdf_subtitles(bdf_file)
    domain_to_subcase = {} # Map internal DOMAIN_ID to actual SUBCASE ID
    h5_subtitles = {} # Fallback dictionary if BDF is missing but H5 has titles
    
    # --- Read the DOMAINS table (The Bridge) ---
    try:
        if hasattr(h5.root.NASTRAN.RESULT, 'DOMAINS'):
            domains_table = h5.root.NASTRAN.RESULT.DOMAINS.read()
            cols_dom = domains_table.dtype.names
            for row in domains_table:
                d_id = row['ID'] # Get internal DOMAIN ID
                sub_id = row['SUBCASE'] if 'SUBCASE' in cols_dom else d_id # Get actual SUBCASE ID
                domain_to_subcase[d_id] = sub_id
                
                # Check if Nastran stored the title directly inside the H5 file
                for t_col in ['SUBTITLE', 'TITLE', 'LABEL']:
                    if t_col in cols_dom:
                        val = row[t_col]
                        clean_val = clean_subtitle(val)
                        if clean_val:
                            h5_subtitles[sub_id] = f"Subcase {sub_id}: {clean_val}"
                            break
    except Exception: 
        pass

    def get_load_case_name(domain_id):
        """ Helper function to translate DOMAIN_ID to the correct Load Case string """
        real_subcase = domain_to_subcase.get(domain_id, domain_id)
        # Priority: 1. BDF Name -> 2. H5 Internal Name -> 3. Default "Subcase X"
        if real_subcase in bdf_subtitles: 
            return bdf_subtitles[real_subcase]
        elif real_subcase in h5_subtitles: 
            return h5_subtitles[real_subcase]
        else: 
            return f"Subcase {real_subcase}"

    # --- Extract Nodal Displacement Data ---
    try:
        data_disp = h5.root.NASTRAN.RESULT.NODAL.DISPLACEMENT.read()
        if 'DOMAIN_ID' in data_disp.dtype.names:
            # Map the names
            df_disp['Load_Case'] = [get_load_case_name(d_id) for d_id in data_disp['DOMAIN_ID']]
        for col in data_disp.dtype.names:
            if col in DEF_DISP: 
                df_disp[DEF_DISP[col]] = data_disp[col]
        if 'Tx' in df_disp.columns:
            # Calculate Total Magnitude (Vector Sum)
            df_disp['Total Mag'] = np.sqrt(df_disp['Tx']**2 + df_disp['Ty']**2 + df_disp['Tz']**2)
    except Exception: 
        pass 

    df_raw_list = []
    df_calc_list = []
    
    # --- Extract Elemental Stress Data (The Core Operation) ---
    try:
        stress_node = h5.root.NASTRAN.RESULT.ELEMENTAL.STRESS
        available_elements = list(stress_node._v_children.keys()) # Get all element types (QUAD4, HEXA, etc.)
        if not available_elements: 
            h5.close()
            return None, None, None

        # Loop through each element type found in the model
        for elem_name in available_elements:
            data = getattr(stress_node, elem_name).read()
            cols = data.dtype.names
            
            if 'EID' not in cols: 
                continue # Skip if no Element ID column
            
            df_temp_raw = pd.DataFrame()
            df_temp_raw['Element ID'] = data['EID']
            df_temp_raw['Element Type'] = elem_name
            df_temp_raw['Load_Case'] = [get_load_case_name(d_id) for d_id in data['DOMAIN_ID']] if 'DOMAIN_ID' in cols else "Subcase 1"
            
            vm_matrix = None
            dim_type = "Unknown"
            
            # Smart Detection: Identify the element's physics dimension based on column signatures
            if all(c in cols for c in ['X', 'Y', 'Z', 'TXY', 'TYZ', 'TZX']):
                # 3D Solid Elements (Hexa, Tetra, Penta)
                sx, sy, sz = data['X'], data['Y'], data['Z']
                txy, tyz, tzx = data['TXY'], data['TYZ'], data['TZX']
                vm_matrix = np.sqrt(0.5 * ((sx-sy)**2 + (sy-sz)**2 + (sz-sx)**2 + 6*(txy**2 + tyz**2 + tzx**2)))
                dim_type = "3D_Solid"
                
            elif all(c in cols for c in ['X', 'Y', 'TXY']):
                # 2D Shell Elements (Midplane only)
                sx, sy, txy = data['X'], data['Y'], data['TXY']
                vm_matrix = np.sqrt(sx**2 + sy**2 - sx*sy + 3*(txy**2))
                dim_type = "2D_Shell"
                
            elif all(c in cols for c in ['X1', 'Y1', 'TXY1', 'X2', 'Y2', 'TXY2']):
                # 2D Shell Elements (Top and Bottom surfaces)
                sx1, sy1, txy1 = data['X1'], data['Y1'], data['TXY1']
                vm1 = np.sqrt(sx1**2 + sy1**2 - sx1*sy1 + 3*(txy1**2)) # Top surface Von Mises
                
                sx2, sy2, txy2 = data['X2'], data['Y2'], data['TXY2']
                vm2 = np.sqrt(sx2**2 + sy2**2 - sx2*sy2 + 3*(txy2**2)) # Bottom surface Von Mises
                
                vm_matrix = np.maximum(vm1, vm2) # Take the worst (maximum) between Top and Bottom
                dim_type = "2D_Shell_TopBottom"
                
            elif all(c in cols for c in ['AX', 'MAX', 'MIN', 'XC', 'XD']):
                # 1D Bar Elements
                vm_matrix = np.maximum(np.abs(data['MAX']), np.abs(data['MIN']))
                dim_type = "1D_Bar"
                
            elif 'AXIAL' in cols:
                # 1D Rod Elements
                vm_matrix = np.abs(data['AXIAL'])
                dim_type = "1D_Line"
                
            elif 'X' in cols and 'Y' not in cols:
                # Other 1D line elements
                vm_matrix = np.abs(data['X'])
                dim_type = "1D_Line"
                
            else: 
                continue # Skip unsupported elements (e.g., Rigid, Spring, Bushing)

            # Unpack array matrices into individual columns (Center, Corner_1, Corner_2, etc.)
            for c in cols:
                if c in ['EID', 'DOMAIN_ID', 'TERM', 'GRID']: 
                    continue 
                arr = data[c]
                if len(arr.shape) > 1: # If it's a matrix (multiple nodes per element)
                    for i in range(arr.shape[1]): 
                        df_temp_raw[f"{c}_{'Center' if i==0 else f'Corner_{i}'}"] = arr[:, i]
                else: 
                    df_temp_raw[c] = arr # If it's a single value (center only)

            # Determine the maximum Von Mises stress for each element
            if len(vm_matrix.shape) > 1:
                vm_max = np.max(vm_matrix, axis=1) # Get highest stress among all corners/center
                for i in range(vm_matrix.shape[1]): 
                    df_temp_raw[f"VonMises_{'Center' if i==0 else f'Corner_{i}'}"] = vm_matrix[:, i]
            else:
                vm_max = vm_matrix 
                df_temp_raw["VonMises_Center"] = vm_max
            
            # Create a concise DataFrame for the actual calculation
            df_temp_calc = pd.DataFrame({
                'Load_Case': df_temp_raw['Load_Case'], 
                'Element ID': data['EID'],
                'Element Type': elem_name,
                'Dimension': dim_type,
                'Linear_VonMises_Max': vm_max
            })
            
            df_raw_list.append(df_temp_raw)
            df_calc_list.append(df_temp_calc)
            
        if not df_calc_list: 
            h5.close()
            return None, None, None
            
        # Combine all element types into one large master table
        df_raw = pd.concat(df_raw_list, ignore_index=True)
        df_calc = pd.concat(df_calc_list, ignore_index=True)
        
        # RAM Optimization: Convert repetitive string columns into Categorical format to save huge memory
        df_raw['Load_Case'] = df_raw['Load_Case'].astype('category')
        df_raw['Element Type'] = df_raw['Element Type'].astype('category')
        df_calc['Load_Case'] = df_calc['Load_Case'].astype('category')
        df_calc['Element Type'] = df_calc['Element Type'].astype('category')
        
        # Sort data by Load Case, and put the highest stress at the top (descending)
        df_calc = df_calc.sort_values(['Load_Case', 'Linear_VonMises_Max'], ascending=[True, False]).reset_index(drop=True)

    except Exception as e: 
        print(f"  -> Fatal error: {e}")
        h5.close()
        return None, None, None
        
    h5.close() # Always close the H5 file to prevent memory leaks
    return df_disp, df_raw, df_calc

def convert_stress_to_mpa(df_raw, df_calc, factor):
    """ Converts all stress values based on the user-selected unit conversion factor """
    if factor == 1.0: 
        return df_raw, df_calc
        
    df_r, df_c = df_raw.copy(), df_calc.copy()
    
    # Multiply every numerical column in raw data by the factor
    for col in df_r.columns:
        if df_r[col].dtype.kind == 'f': 
            df_r[col] = df_r[col] * factor
            
    # Multiply the calculation data by the factor
    df_c['Linear_VonMises_Max'] = df_c['Linear_VonMises_Max'] * factor
    
    return df_r, df_c

# ==============================================================================
# 4. NEUBER SOLVER ENGINE
# ==============================================================================
def run_neuber_analysis(df_calc):
    """ Executes the Neuber correction logic on the compiled data """
    res = {'stress':[], 'status':[], 'reduct':[], 'e_elas':[], 'e_plas':[], 'e_tot':[], 'mos':[]}
    
    # Iterate through stress and dynamic material properties row by row
    data_iterator = zip(df_calc['Linear_VonMises_Max'], df_calc['E'], df_calc['Fty'], df_calc['Ftu'], df_calc['n'])
    
    # Loop with TQDM progress bar
    for s_lin, E_mod, Fty, Ftu, n_exp in tqdm(data_iterator, total=len(df_calc), desc="  -> Crunching Neuber Math", unit="elem"):
        # Skip invalid or negative stress data
        if pd.isna(s_lin) or s_lin <= 0:
            for k in res: res[k].append(0 if k != 'status' else "No Data")
            continue
        
        is_plastic = s_lin > Fty # Check if stress exceeds Yield Strength
        
        if is_plastic:
            # Apply Neuber correction
            s_corr = solve_neuber_mmpds(s_lin, E_mod, Fty, n_exp)
            status = "PLASTIC (Neuber Corrected)"
        else:
            # Keep linear stress if safe
            s_corr = s_lin 
            status = "Elastic (Linear)"
            
        # Calculate Strain results
        e_tot = get_strain_ramberg(s_corr, E_mod, Fty, n_exp)
        e_elas = s_corr / E_mod
        e_plas = max(e_tot - e_elas, 0.0) 
        
        # Calculate stress reduction percentage and Margin of Safety against Ultimate Strength
        reduct = ((s_lin - s_corr)/s_lin)*100 if s_lin > 0 else 0 
        mos = (Ftu / s_corr) - 1 if s_corr > 0 else 999.9 
            
        res['stress'].append(s_corr)
        res['status'].append(status)
        res['reduct'].append(reduct)
        res['e_elas'].append(e_elas)
        res['e_plas'].append(e_plas)
        res['e_tot'].append(e_tot)
        res['mos'].append(mos)

    # Append results as new columns to the DataFrame
    df_out = df_calc.copy()
    df_out['Neuber_Stress'] = res['stress']
    df_out['MoS_Corrected'] = res['mos']
    df_out['Reduction_%'] = res['reduct']
    df_out['Elastic_Strain'] = res['e_elas']
    df_out['Plastic_Strain'] = res['e_plas']
    df_out['Total_Strain'] = res['e_tot']
    df_out['Status'] = res['status']
    
    gc.collect() # Trigger garbage collection to free RAM
    return df_out

# ==============================================================================
# 5. VISUALIZATION (OVERALL + PER LOAD CASE) WITH DETAILED LEGENDS
# ==============================================================================
def create_plots(df, base_name, mat_defaults):
    """ Generates all Matplotlib & Seaborn plots and saves them as .png files """
    print("\n[STEP 6] 🎨 Generating High-Res Visualizations (with clear Legends)...")
    sns.set_style("whitegrid") # Use clean grid style for all plots
    
    # Dictionary to keep track of generated image filenames
    generated_images = {
        "material": "G0_Material_Curve.png", 
        "overall_scatter": "G0_Overall_Scatter.png", 
        "overall_intersect": "G0_Overall_Intersections.png",
        "loadcases": {}
    }
    
    E_def, Fty_def, Ftu_def, n_def = mat_defaults['E'], mat_defaults['Fty'], mat_defaults['Ftu'], mat_defaults['n']

    # --- PLOT 1: BASE MATERIAL CURVE ---
    s_range = np.linspace(0, Ftu_def*1.1, 200) # Generate stress axis points
    e_range = get_strain_ramberg(s_range, E_def, Fty_def, n_def) # Generate strain axis points
    
    plt.figure(figsize=(9, 5)) 
    plt.plot(e_range, s_range, 'b-', linewidth=2.5, label='Ramberg-Osgood Material Curve')
    plt.plot(s_range/E_def, s_range, 'k--', linewidth=1.5, label="Elastic Line (Hooke's Law)")
    plt.axhline(Fty_def, c='r', ls=':', linewidth=2, label=f'Yield Strength ({Fty_def:,.0f} MPa)')
    plt.axhline(Ftu_def, c='purple', ls='--', linewidth=2, label=f'Ultimate Strength ({Ftu_def:,.0f} MPa)')
    
    plt.title("Material Stress-Strain Curve (Default Mat)", fontsize=12, fontweight='bold')
    plt.xlabel("Strain [mm/mm]", fontweight='bold')
    plt.ylabel("Stress [MPa]", fontweight='bold')
    # Place legend outside the plot area
    plt.legend(bbox_to_anchor=(1.04, 0.5), loc="center left", borderaxespad=0, title="Line Symbols") 
    plt.grid(True, alpha=0.4)
    plt.tight_layout()
    plt.savefig(generated_images["material"], dpi=150, bbox_inches='tight')
    plt.close()

    # Generate unique colors for load cases
    load_cases = df['Load_Case'].unique()
    colors_palette = sns.color_palette("tab10", len(load_cases))

    # --- PLOT 2: OVERALL SCATTER (ALL LOAD CASES COMBINED) ---
    plt.figure(figsize=(10, 6))
    if len(load_cases) > 1:
        # Plot with Seaborn, using Load_Case as the color hue
        sns.scatterplot(data=df, x='Linear_VonMises_Max', y='Neuber_Stress', hue='Load_Case', palette='tab10', alpha=0.6, s=30, edgecolor=None)
    else:
        plt.scatter(df['Linear_VonMises_Max'], df['Neuber_Stress'], c='#1F77B4', alpha=0.6, s=30, label=load_cases[0])
        
    plt.plot([0, df['Linear_VonMises_Max'].max()*1.05], [0, df['Linear_VonMises_Max'].max()*1.05], 'k--', linewidth=1.5, label='Linear Elastic Line (1:1 Ratio)')
    
    plt.title(f"OVERALL Stress Correction Overview\nFile: {base_name}.h5", fontsize=12, fontweight='bold')
    plt.xlabel("Linear Stress [MPa]", fontweight='bold')
    plt.ylabel("Neuber Stress [MPa]", fontweight='bold')
    plt.legend(bbox_to_anchor=(1.04, 0.5), loc="center left", borderaxespad=0, title="Load Cases & Lines")
    plt.tight_layout()
    plt.savefig(generated_images["overall_scatter"], dpi=150, bbox_inches='tight')
    plt.close()

    # --- PLOT 3: OVERALL WORST INTERSECTIONS ---
    plt.figure(figsize=(10, 6))
    plt.plot(e_range, s_range, 'k-', alpha=0.2, linewidth=3, label='Base Material Curve')
    plt.plot(s_range/E_def, s_range, 'k--', alpha=0.2, label='Base Elastic Line')
    
    has_plastic = False
    for i, lc in enumerate(load_cases):
        # Find plastic elements for this load case
        df_lc = df[(df['Load_Case'] == lc) & (df['Status'].str.contains('PLASTIC'))]
        if not df_lc.empty:
            has_plastic = True
            worst = df_lc.iloc[0] # Take the absolute worst element (Top 1)
            s_lin, s_neu = worst['Linear_VonMises_Max'], worst['Neuber_Stress']
            e_lin, e_neu = s_lin / worst['E'], worst['Total_Strain']
            
            # Plot the specific Neuber intersection points for this load case
            plt.plot(e_lin, s_lin, 'o', color=colors_palette[i], alpha=0.5) 
            plt.plot(e_neu, s_neu, 'X', color=colors_palette[i], markersize=10, markeredgecolor='k', label=f"Max Stress: {lc}")
            
            # Plot the Neuber Hyperbola line connecting linear to neuber point
            e_hyp = np.linspace(e_lin, e_neu*1.1, 50)
            plt.plot(e_hyp, (s_lin*e_lin)/e_hyp, ':', color=colors_palette[i], alpha=0.7)
            
    plt.title(f"OVERALL Worst Intersections (All Load Cases)\nFile: {base_name}.h5", fontsize=12, fontweight='bold')
    plt.xlabel("Strain [mm/mm]", fontweight='bold')
    plt.ylabel("Stress [MPa]", fontweight='bold')
    
    if has_plastic: 
        plt.legend(bbox_to_anchor=(1.04, 0.5), loc="center left", borderaxespad=0, title="Symbols (X = Neuber Point)")
        
    plt.grid(True, alpha=0.4)
    plt.tight_layout()
    plt.savefig(generated_images["overall_intersect"], dpi=150, bbox_inches='tight')
    plt.close()

    # --- PLOT 4: INDIVIDUAL GRAPHS PER LOAD CASE ---
    for i, lc in enumerate(load_cases):
        df_lc = df[df['Load_Case'] == lc]
        safe_lc = safe_filename(str(lc))
        
        # A. Specific Scatter Plot
        plt.figure(figsize=(9, 5))
        my_pal = {"Elastic (Linear)": "#1F77B4", "PLASTIC (Neuber Corrected)": "#D62728"}
        
        # Use hue='Status' to trigger the legend for Elastic vs Plastic
        sns.scatterplot(data=df_lc, x='Linear_VonMises_Max', y='Neuber_Stress', hue='Status', palette=my_pal, alpha=0.6, s=30)
        plt.plot([0, df_lc['Linear_VonMises_Max'].max() * 1.1], [0, df_lc['Linear_VonMises_Max'].max() * 1.1], 'k--', linewidth=1.5, label='Linear Elastic Line')
        
        plt.title(f"Stress Correction: {lc}", fontsize=11, fontweight='bold')
        plt.xlabel("Linear Stress [MPa]", fontweight='bold')
        plt.ylabel("Neuber Stress [MPa]", fontweight='bold')
        plt.legend(bbox_to_anchor=(1.04, 0.5), loc="center left", borderaxespad=0, title="Element Status")
        plt.tight_layout()
        
        img_scatter = f"G1_Scatter_{i}_{safe_lc}.png"
        plt.savefig(img_scatter, dpi=150, bbox_inches='tight')
        plt.close()
        
        # B. Specific Intersection Plot
        img_intersect = None
        data_plas = df_lc[df_lc['Status'].str.contains('PLASTIC')]
        
        # Only create this plot if plastic elements exist in this load case
        if len(data_plas) > 0:
            worst = data_plas.iloc[0] 
            s_lin_pt, s_neu_pt = worst['Linear_VonMises_Max'], worst['Neuber_Stress']
            e_lin_pt, e_neu_pt = s_lin_pt / worst['E'], worst['Total_Strain']
            
            plt.figure(figsize=(10, 6))
            s_plot = np.linspace(0, s_lin_pt*1.1, 200)
            
            # Plot base curves
            plt.plot(get_strain_ramberg(s_plot, worst['E'], worst['Fty'], worst['n']), s_plot, 'b-', alpha=0.3, linewidth=3, label='Material Curve (Ramberg-Osgood)')
            plt.plot(s_plot/worst['E'], s_plot, 'k--', alpha=0.4, linewidth=2, label='Linear Elastic Line')
            
            # Plot intersection points
            plt.plot(e_lin_pt, s_lin_pt, 'ro', markersize=9, label='Max Linear Stress (Calculated)')
            plt.plot(e_neu_pt, s_neu_pt, 'gX', markersize=11, markeredgecolor='k', label='True Stress (Neuber Corrected)')
            
            # Plot Neuber hyperbola
            energy = s_lin_pt * e_lin_pt
            e_hyp = np.linspace(e_lin_pt, e_neu_pt*1.1, 50)
            plt.plot(e_hyp, energy/e_hyp, 'r:', linewidth=2.5, label='Neuber Hyperbola (Constant Energy)')
            
            plt.title(f"Worst Case Intersection: {lc}\n(Element ID: {int(worst['Element ID'])})", fontsize=11, fontweight='bold')
            plt.xlabel("Strain [mm/mm]", fontweight='bold')
            plt.ylabel("Stress [MPa]", fontweight='bold')
            plt.legend(bbox_to_anchor=(1.04, 0.5), loc="center left", borderaxespad=0, title="Symbols Definition")
            plt.grid(True, alpha=0.4)
            plt.tight_layout()
            
            img_intersect = f"G2_Intersect_{i}_{safe_lc}.png"
            plt.savefig(img_intersect, dpi=150, bbox_inches='tight')
            plt.close()
            
        # Store filenames to insert into Excel later
        generated_images["loadcases"][lc] = {"scatter": img_scatter, "intersect": img_intersect}

    return generated_images

# ==============================================================================
# 6. PREMIUM EXCEL EXPORT 
# ==============================================================================
def save_gold_report(df_disp, df_raw, df_neuber, output_excel, base_name, is_multi_mat, dict_images):
    """ Compiles all data and images into a beautifully formatted Excel workbook """
    print(f"\n[STEP 7] 📑 Compiling Premium Excel Report: {os.path.basename(output_excel)}...")
    writer = pd.ExcelWriter(output_excel, engine='xlsxwriter') 
    wb = writer.book
    
    # --- Define Cell Formats ---
    fmt_title = wb.add_format({'bold':True, 'font_size':16, 'fg_color':'#1F497D', 'font_color':'white', 'border':1, 'align':'center', 'valign':'vcenter'})
    fmt_head  = wb.add_format({'bold':True, 'fg_color':'#2F75B5', 'font_color':'white', 'border':1, 'align':'center', 'valign':'vcenter', 'text_wrap': True})
    fmt_gen   = wb.add_format({'border':1, 'align':'center', 'valign':'vcenter'}) 
    fmt_num2  = wb.add_format({'num_format':'0.00', 'border':1, 'align':'center', 'valign':'vcenter'}) 
    fmt_num6  = wb.add_format({'num_format':'0.000000', 'border':1, 'align':'center', 'valign':'vcenter'}) 
    fmt_red_bg   = wb.add_format({'font_color':'#9C0006', 'bg_color':'#FFC7CE', 'border':1, 'align':'center'}) 
    fmt_green_bg = wb.add_format({'font_color':'#006100', 'bg_color':'#C6EFCE', 'border':1, 'align':'center'}) 
    
    # --- SHEET 1: EXECUTIVE SUMMARY ---
    ws_sum = wb.add_worksheet('Executive_Summary')
    ws_sum.merge_range('B2:I3', f"AEROSPACE STRESS ANALYSIS - NEUBER REPORT", fmt_title)
    ws_sum.write('B4', f"File: {base_name}.h5", wb.add_format({'italic':True}))
    
    # Write Material Info
    mat_status = "MULTIPLE MATERIALS APPLIED" if is_multi_mat else "SINGLE GLOBAL MATERIAL"
    ws_sum.write('B6', "Material Configuration", fmt_head)
    ws_sum.merge_range('C6:E6', mat_status, fmt_gen)

    # Write summary table headers
    headers = ["Load Case", "Worst Element ID", "Mat Fty\n[MPa]", "Max Linear Stress\n[MPa]", "Max Neuber Stress\n[MPa]", "Lowest MoS", "Yielded\nElements", "Total\nAnalyzed"]
    for col, head in enumerate(headers): 
        ws_sum.write(8, 1+col, head, fmt_head)
    ws_sum.set_row(8, 40) 
    
    row_idx = 9
    if 'Load_Case' in df_neuber.columns:
        # Group by load case to find the worst stats for each
        grouped = df_neuber.groupby('Load_Case', observed=True)
        for lc_name, group in grouped:
            if group.empty: continue
            worst_row = group.loc[group['Linear_VonMises_Max'].idxmax()]
            
            ws_sum.write(row_idx, 1, str(lc_name), fmt_gen)
            ws_sum.write(row_idx, 2, worst_row['Element ID'], fmt_gen)
            ws_sum.write(row_idx, 3, worst_row['Fty'], fmt_num2) 
            ws_sum.write(row_idx, 4, worst_row['Linear_VonMises_Max'], fmt_num2)
            ws_sum.write(row_idx, 5, worst_row['Neuber_Stress'], fmt_num2)
            ws_sum.write(row_idx, 6, group['MoS_Corrected'].min(), fmt_num2)
            ws_sum.write(row_idx, 7, len(group[group['Status'].str.contains('PLASTIC')]), fmt_gen)
            ws_sum.write(row_idx, 8, len(group), fmt_gen)
            row_idx += 1
            
    ws_sum.set_column('B:B', 35)
    ws_sum.set_column('C:I', 18)

    # --- WRITER HELPER FOR DATA SHEETS ---
    def write_sheet(df, name, stress_cols=[], strain_cols=[], mos_cols=[]):
        """ Helper function to write a DataFrame to Excel and apply column widths/formats """
        df.to_excel(writer, sheet_name=name, index=False)
        ws = writer.sheets[name]
        ws.autofilter(0, 0, len(df), len(df.columns)-1) # Add AutoFilter
        ws.freeze_panes(1, 0) # Freeze top header row
        
        for i, col in enumerate(df.columns):
            ws.write(0, i, col, fmt_head)
            fmt_col = fmt_gen
            width = 15
            if col == 'Load_Case': width = 30
            elif col in stress_cols: fmt_col = fmt_num2; width = 18
            elif col in strain_cols: fmt_col = fmt_num6; width = 18
            elif col in mos_cols: fmt_col = fmt_num2; width = 15
            ws.set_column(i, i, width, fmt_col)
        return ws

    # Rename columns for clarity in Excel
    df_neuber_renamed = df_neuber.rename(columns={
        'Linear_VonMises_Max': 'Linear_Stress [MPa]',
        'Neuber_Stress': 'Neuber_Stress [MPa]',
        'MoS_Corrected': 'MoS_Corrected [Ult]',
        'Reduction_%': 'Reduction [%]',
        'Elastic_Strain': 'Elastic_Strain [mm/mm]',
        'Plastic_Strain': 'Plastic_Strain [mm/mm]',
        'Total_Strain': 'Total_Strain [mm/mm]'
    })
    
    # Categorize columns for formatting
    stress_cols = ['Linear_Stress [MPa]', 'Neuber_Stress [MPa]', 'E', 'Fty', 'Ftu']
    strain_cols = ['Elastic_Strain [mm/mm]', 'Plastic_Strain [mm/mm]', 'Total_Strain [mm/mm]', 'Reduction [%]']
    mos_cols    = ['MoS_Corrected [Ult]']
    raw_stress_cols = [c for c in df_raw.columns if 'Von' in c or 'S' in c or 'T' in c or 'X' in c or 'Y' in c or 'MAX' in c or 'MIN' in c]

    # --- SHEETS 2, 3, 4: WRITE DATA TABS ---
    if df_disp is not None and not df_disp.empty: 
        write_sheet(df_disp, 'Displacement')
        
    write_sheet(df_raw, 'Raw_Stress_Data_MPa', stress_cols=raw_stress_cols)
    ws_neu = write_sheet(df_neuber_renamed, 'Neuber_Analysis', stress_cols, strain_cols, mos_cols)
    
    # Apply Conditional Formatting to the Neuber tab
    last_row = len(df_neuber) + 1
    stat_col = xl_col_to_name(df_neuber_renamed.columns.get_loc("Status"))
    ws_neu.conditional_format(f'{stat_col}2:{stat_col}{last_row}', {'type':'text', 'criteria':'containing', 'value':'PLASTIC', 'format':fmt_red_bg})
    ws_neu.conditional_format(f'{stat_col}2:{stat_col}{last_row}', {'type':'text', 'criteria':'containing', 'value':'Elastic', 'format':fmt_green_bg})
    
    mos_col = xl_col_to_name(df_neuber_renamed.columns.get_loc("MoS_Corrected [Ult]"))
    ws_neu.conditional_format(f'{mos_col}2:{mos_col}{last_row}', {'type':'cell', 'criteria':'<', 'value':0, 'format':fmt_red_bg})
    
    strs_col = xl_col_to_name(df_neuber_renamed.columns.get_loc("Neuber_Stress [MPa]"))
    ws_neu.conditional_format(f'{strs_col}2:{strs_col}{last_row}', {'type':'data_bar', 'bar_color':'#63C384'})

    # --- SHEET 5: VISUAL GRAPHS (ALWAYS PLACED LAST) ---
    ws_g = wb.add_worksheet('Visual_Graphs')
    ws_g.merge_range('B2:M3', "COMPREHENSIVE VISUALIZATION REPORT", fmt_title)
    ws_g.hide_gridlines(2)
    
    # Insert Overall Summary Graphs at the top
    ws_g.write('B5', "🌐 OVERALL GLOBAL RESULTS", wb.add_format({'bold':True, 'font_size':14, 'bg_color':'#FFD966', 'border':1}))
    if os.path.exists(dict_images['overall_scatter']): ws_g.insert_image('B7', dict_images['overall_scatter'])
    if os.path.exists(dict_images['overall_intersect']): ws_g.insert_image('O7', dict_images['overall_intersect'])
    if os.path.exists(dict_images['material']): ws_g.insert_image('B36', dict_images['material'])
    
    # Insert Specific Graphs per Load Case below
    row_img = 65
    for lc, imgs in dict_images['loadcases'].items():
        ws_g.write(f'B{row_img}', f"📈 RESULTS FOR: {lc}", wb.add_format({'bold':True, 'font_size':14, 'bg_color':'#D9E1F2', 'border':1}))
        if imgs['scatter'] and os.path.exists(imgs['scatter']): ws_g.insert_image(f'B{row_img+2}', imgs['scatter'])
        if imgs['intersect'] and os.path.exists(imgs['intersect']): ws_g.insert_image(f'O{row_img+2}', imgs['intersect'])
        row_img += 33 # Spacing for the next load case block

    writer.close() # Save Excel File
    
    # Cleanup: Delete PNG files from folder after pasting them into Excel to keep directory clean
    try:
        os.remove(dict_images['material'])
        os.remove(dict_images['overall_scatter'])
        os.remove(dict_images['overall_intersect'])
        for lc, imgs in dict_images['loadcases'].items():
            if imgs['scatter']: os.remove(imgs['scatter'])
            if imgs['intersect']: os.remove(imgs['intersect'])
    except: pass

# ==============================================================================
# 7. MANUAL CALCULATOR (MODE 2 RESTORED)
# ==============================================================================
def manual_neuber_input():
    """ Provides a quick command-line tool to calculate Neuber for a single stress value """
    print("\n" + "═"*55)
    print(" 🧮 MANUAL NEUBER CALCULATOR (SINGLE POINT)")
    print("═"*55)
    
    try:
        # Ask user for Material Inputs
        val_E   = float(input("  Young's Modulus (E) [MPa] : "))
        val_Fty = float(input("  Yield Strength (Fty) [MPa]: "))
        val_Ftu = float(input("  Ultimate Str (Ftu) [MPa]  : "))
        n_input = input("  Hardening (n) [Enter: 15] : ").strip()
        val_n   = float(n_input) if n_input else 15.0
        
        # Ask user for Unit Preferences
        print("\n  [Unit Selection]")
        print("  [1] Pascal (Pa)")
        print("  [2] Megapascal (MPa) - Default")
        print("  [3] Gigapascal (GPa)")
        print("  [4] PSI (Pounds per Square Inch)")
        unit_choice = input("  Select (1/2/3/4): ").strip()
        to_mpa_dict = {'1': 1e-6, '2': 1.0, '3': 1000.0, '4': 0.00689475729} 
        unit_names = {'1': 'Pa', '2': 'MPa', '3': 'GPa', '4': 'PSI'}
        conv_factor = to_mpa_dict.get(unit_choice, 1.0)
        stress_unit = unit_names.get(unit_choice, 'MPa')
        
        # Ask for the single stress value
        s_lin_input = float(input(f"\n  Enter Max Linear Stress [{stress_unit}]: "))
    except ValueError:
        print("  [!] Input must be a number. Program aborted.")
        return
    
    # Calculate Logic
    s_lin_mpa = s_lin_input * conv_factor
    is_plastic = s_lin_mpa > val_Fty
    
    if is_plastic:
        s_corr = solve_neuber_mmpds(s_lin_mpa, val_E, val_Fty, val_n)
        status = "PLASTIC (Neuber Corrected)"
    else:
        s_corr = s_lin_mpa
        status = "ELASTIC (Linear, No correction needed)"
        
    e_tot = get_strain_ramberg(s_corr, val_E, val_Fty, val_n)
    e_elas = s_corr / val_E
    e_plas = max(e_tot - e_elas, 0.0)
    reduct_pct = ((s_lin_mpa - s_corr) / s_lin_mpa) * 100 if s_lin_mpa > 0 else 0.0
    mos = (val_Ftu / s_corr) - 1 if s_corr > 0 else 999.9
    
    # Print Output Results
    print("\n" + "═"*55)
    print(" 📊 NEUBER ANALYSIS RESULTS")
    print("═"*55)
    print(f"  Status           : {status}")
    if stress_unit != 'MPa':
        print(f"  Linear Input     : {s_lin_input:,.2f} {stress_unit} --> ({s_lin_mpa:,.2f} MPa)")
    else:
        print(f"  Linear Input     : {s_lin_input:,.2f} MPa")
    print(f"  Actual Stress    : {s_corr:,.2f} MPa")
    print(f"  Stress Reduction : {reduct_pct:.2f} %") 
    print(f"  Total Strain     : {e_tot:.6f} mm/mm")
    print(f"  Margin of Safety : {mos:.2f} (Against Ultimate Strength)")
    print("═══════════════════════════════════════════════════════\n")

# ==============================================================================
# 8. MAIN UI / CLI APPLICATION FLOW
# ==============================================================================
def main():
    """ The core execution loop connecting all UI interfaces and logic functions """
    os.system('cls' if os.name == 'nt' else 'clear') # Clear terminal screen
    print("╔═════════════════════════════════════════════════════════════════╗")
    print("║      🚀 AEROSPACE NEUBER ANALYSIS SUITE (ULTIMATE EDITION)      ║")
    print("╚═════════════════════════════════════════════════════════════════╝")
    print("Select the operation mode you want to use:")
    print("  [1] 📁 Analyze .h5 File from Nastran (Full Batch Processing)")
    print("  [2] 🧮 Manual Calculator (Input 1 Custom Stress Value)")
    
    mode = input("\n  -> Enter choice (1 or 2): ").strip()
    
    if mode == '2':
        manual_neuber_input() # Run Manual Mode
        return
        
    elif mode == '1': # Run H5 Batch Mode
        script_dir = os.path.dirname(os.path.abspath(__file__)) # Get current folder
        
        # --- [STEP 1] DATA SELECTION ---
        print("\n[STEP 1] 📁 DATA SELECTION")
        h5_files = glob.glob(os.path.join(script_dir, "*.h5")) # Find all .h5 files
        if not h5_files:
            print(f"  [X] No .h5 files found in folder:\n{script_dir}"); return

        if len(h5_files) == 1:
            selected_h5 = h5_files[0]
            print(f"  -> Auto-selected the only H5 file: {os.path.basename(selected_h5)}")
        else:
            for idx, file in enumerate(h5_files): print(f"  [{idx + 1}] {os.path.basename(file)}")
            try: choice = int(input("  -> Select H5 file number: ").strip()); selected_h5 = h5_files[choice - 1]
            except: print("  [X] Invalid input. Aborting."); return

        bdf_files = glob.glob(os.path.join(script_dir, "*.bdf")) + glob.glob(os.path.join(script_dir, "*.dat"))
        selected_bdf = None
        if bdf_files:
            print("\n  📝 Load Case Names (Subtitles) available from:")
            print("  [0] Skip (Use default IDs)")
            for idx, file in enumerate(bdf_files): print(f"  [{idx + 1}] {os.path.basename(file)}")
            try:
                choice = int(input("  -> Select BDF/DAT file number for Subtitles: ").strip())
                if choice > 0: selected_bdf = bdf_files[choice - 1]
            except: pass

        # --- [STEP 2] PRE-SCAN ---
        print("\n[STEP 2] 🔍 PRE-SCANNING MODEL")
        # Read the database and extract raw arrays
        df_d, df_r, df_c = extract_h5_data(selected_h5, bdf_file=selected_bdf)
        if df_c is None or df_c.empty:
            print("  [X] File is empty or invalid."); return

        # --- [STEP 3] UNIT CONVERSION ---
        print("\n[STEP 3] ⚖️ UNIT CONVERSION")
        max_stress_sample = df_c['Linear_VonMises_Max'].max()
        print(f"  -> Max Linear Stress detected: {max_stress_sample:,.2f}")
        print("  What unit was exported by Nastran?")
        print("  [1] Pascal (Pa)")
        print("  [2] Megapascal (MPa) - Default")
        print("  [3] Gigapascal (GPa)")
        print("  [4] PSI (Pounds per Square Inch)")
        
        while True:
            unit_choice = input("  Select unit (1/2/3/4): ").strip()
            if unit_choice == '1': conv_factor = 1e-6; break
            elif unit_choice == '2': conv_factor = 1.0; break
            elif unit_choice == '3': conv_factor = 1000.0; break
            elif unit_choice == '4': conv_factor = 0.00689475729; break
            elif unit_choice == '': conv_factor = 1.0; break # Enter default = MPa
            else: print("  [!] Invalid choice.")

        # --- [STEP 4] DYNAMIC MULTI-MATERIAL CONFIGURATION ---
        print("\n[STEP 4] ⚙️ MATERIAL CONFIGURATION")
        print("  IMPORTANT: Please consistently enter material properties in MPa!")
        try:
            print("  How many materials are used in this model?")
            num_mats = int(input("  -> Enter number (e.g., 1 for single material, 2 for multi-material): ").strip())
        except ValueError: num_mats = 1
        
        is_multi_mat = num_mats > 1
        
        # Initialize default material columns
        df_c['E'] = 0.0; df_c['Fty'] = 0.0; df_c['Ftu'] = 0.0; df_c['n'] = 15.0
        mat_defaults = {}

        # Loop through user inputs for each material
        for m in range(1, num_mats + 1):
            if is_multi_mat:
                print(f"\n  --- PROPERTI MATERIAL {m} ---")
                if m == 1: print("  (Material 1 akan menjadi DEFAULT MATERIAL untuk seluruh elemen)")
            else:
                print("\n  --- PROPERTI MATERIAL ---")
                
            try:
                val_E = float(input("  Young's Modulus (E) [MPa]   : "))
                val_Fty = float(input("  Yield Strength (Fty) [MPa]  : "))
                val_Ftu = float(input("  Ultimate Str (Ftu) [MPa]    : "))
                n_inp = input("  Hardening (n) [Enter for 15]: ").strip()
                val_n = float(n_inp) if n_inp else 15.0
                
                if m == 1:
                    # Apply globally as the fallback default
                    df_c['E'] = val_E; df_c['Fty'] = val_Fty; df_c['Ftu'] = val_Ftu; df_c['n'] = val_n
                    mat_defaults = {'E': val_E, 'Fty': val_Fty, 'Ftu': val_Ftu, 'n': val_n}
                else:
                    # Target specific elements for alternative materials
                    print(f"  -> Material {m} diaplikasikan untuk Element ID berapa?")
                    print("  -> (Contoh format: 1-500, 1001, 2000-2500)")
                    range_str = input("  -> Element ID Range: ").strip()
                    target_ids = parse_element_ranges(range_str)
                    
                    if target_ids:
                        # Overwrite material properties specifically where Element ID matches user target
                        mask = df_c['Element ID'].isin(target_ids)
                        df_c.loc[mask, 'E'] = val_E; df_c.loc[mask, 'Fty'] = val_Fty
                        df_c.loc[mask, 'Ftu'] = val_Ftu; df_c.loc[mask, 'n'] = val_n
                        print(f"  -> [OK] Material {m} applied to {mask.sum()} elements.")
            except ValueError:
                print("  [X] Invalid number. Using default parameters.")

        # --- [STEP 5] OUTPUT OPTIMIZATION ---
        print("\n[STEP 5] 📊 OUTPUT FILTERING")
        try:
            top_n_inp = input("  -> Export Top 'N' worst elements per load case? (0 for ALL): ").strip()
            top_n = int(top_n_inp) if top_n_inp else 0
        except: top_n = 0
            
        print("\n" + "═"*65)
        print(" 🚀 INITIATING ENGINE (SINGLE-CORE OPTIMIZED)...")
        
        # Prep the Excel file to prevent "File is Open" permission errors at the end
        base_name = os.path.splitext(os.path.basename(selected_h5))[0]
        output_excel = os.path.join(script_dir, f"Report_Neuber_{base_name}.xlsx")
        try: open(output_excel, 'a').close()
        except: print(f"\n[ERROR] Close the file {os.path.basename(output_excel)} first!"); return
        
        # Convert all parsed stress to MPa
        df_r_conv, df_c_conv = convert_stress_to_mpa(df_r, df_c, conv_factor) 
        
        # Filter down to top N rows if requested
        if top_n > 0:
            df_c_conv = df_c_conv.groupby('Load_Case', observed=True).head(top_n).reset_index(drop=True)
            df_r_conv = df_r_conv[df_r_conv['Element ID'].isin(df_c_conv['Element ID'])]
            
        # CALCULATE NEUBER 
        df_n = run_neuber_analysis(df_c_conv)
        
        # GENERATE PLOTS & SAVE REPORT
        os.chdir(script_dir) 
        dict_images = create_plots(df_n, base_name, mat_defaults)
        save_gold_report(df_d, df_r_conv, df_n, output_excel, base_name, is_multi_mat, dict_images)
        
        print("\n" + "═"*65)
        print(f" 🎉 SUCCESS! EXCEL GENERATED: {os.path.basename(output_excel)}")
        print("═"*65 + "\n")

if __name__ == "__main__":
    main() # Execute the program
